# Generated by Django 3.2.7 on 2021-11-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('standard', models.CharField(max_length=255)),
                ('english', models.FloatField(default=0)),
                ('physics', models.FloatField(default=0)),
                ('maths', models.FloatField(default=0)),
                ('chemistry', models.FloatField(default=0)),
                ('biology', models.FloatField(default=0)),
                ('history', models.FloatField(default=0)),
                ('geography', models.FloatField(default=0)),
            ],
        ),
    ]
