# Generated by Django 3.2.7 on 2021-11-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDetails',
            new_name='StudentDetail',
        ),
    ]
