# Generated by Django 3.2.7 on 2021-11-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_api', '0002_rename_studentdetails_studentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('marks', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='biology',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='chemistry',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='english',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='history',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='maths',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='physics',
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='marks',
            field=models.ManyToManyField(to='stud_api.Mark'),
        ),
    ]
